### ISSUE TITLE
Please provide a linux executable

### ISSUE THREAD

**Issue by nalinipradash** [Ashutosh2003/Operator-Fill#4]
As this project is getting popular, you should consider providing a linux executable file alongside the windows executable.
P.S.: Thank you for this project.

**Comment by AsutoSSH** [comment]
> As this project is getting popular, you should consider providing a linux executable file alongside the windows executable.
> P.S.: Thank you for this project.
> 
For now compiling and running is the only option for linux. I dont know how to make a makefile for installing or a official package for AUR (Arch) or other repositories. Also I dont know if a common .out file will run on all linux distros😅.
